small_inputs = [
    # {"map": [['P', 'P', 'P'],
    #          ['I', 'G', 'P'],
    #          ['P', 'P', 'P'], ],
    #  "taxis": {'taxi 1': {"location": (0, 0),
    #                       "fuel": 15,
    #                       "capacity": 2}},
    #  "passengers": {'Dana': {"location": (1, 1),
    #                          "destination": (0, 2),
    #                          "possible_goals": ((0, 2), (2, 0)),
    #                          "prob_change_goal": 0.3}},
    #  "turns to go": 100},

    {"map": [['P', 'P', 'I', 'P'],
             ['P', 'P', 'P', 'P'],
             ['P', 'I', 'G', 'P'],
             ['P', 'P', 'P', 'P'], ],
     "taxis": {'taxi 1': {"location": (3, 3),
                          "fuel": 15,
                          "capacity": 2},
               'taxi 2': {"location": (3, 3),
                          "fuel": 15,
                          "capacity": 2}},
     "passengers": {'Dana': {"location": (3, 3),
                             "destination": (2, 3),
                             "possible_goals": ((5, 5), (4, 5), (3, 3)),
                             "prob_change_goal": 0.05}},
     "turns to go": 100}
]
